ZSH_HOME=$HOME/dotfiles/zsh/rc
. $ZSH_HOME/keybind.zsh
. $ZSH_HOME/directory.zsh
. $ZSH_HOME/completion.zsh
. $ZSH_HOME/prompt.zsh
. $ZSH_HOME/plugins.zsh
. $ZSH_HOME/nvim.zsh
. $ZSH_HOME/history.zsh
. $ZSH_HOME/git.zsh
. $ZSH_HOME/path.zsh
. $ZSH_HOME/android.zsh
. $ZSH_HOME/buffer.zsh
. $ZSH_HOME/ctags.zsh
. $ZSH_HOME/docker.zsh
. $ZSH_HOME/kubernetes.zsh
